---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  namespace: orchesto
  labels:
    app: postgres
data:
  POSTGRES_DB: orchesto
  POSTGRES_USER: orchesto
  POSTGRES_PASSWORD: orchesto
  POSTGRES_INITDB_ARGS: "-E 'UTF-8' --locale=C"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: orchesto
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: orchesto
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: orchesto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: orchesto
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
